runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: data-visualization-cloud:us-central1:cloud-sql-database
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: root
# [END env_variables]
